# Generated by Django 5.0.6 on 2024-06-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='departmentName',
        ),
    ]
