# Generated by Django 5.0.6 on 2024-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0005_studentprofile_enrollment_status'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='student',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='students',
            field=models.ManyToManyField(related_name='chat_rooms', to='auth_account.studentprofile'),
        ),
    ]
