# Generated by Django 5.0.6 on 2024-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0004_alter_studentprofile_parent_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_status',
            field=models.BooleanField(default=False),
        ),
    ]
